djangopokemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

# this like app.use() in express
urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('pokemon/', views.Poke_List.as_view(), name="poke_list"),
    path('about/', views.About.as_view(), name="about"),
    path('pokemon/new/', views.Poke_Create.as_view(), name="poke_create"),
    path('pokemon/<int:pk>/', views.Poke_Detail.as_view(), name="poke_detail"),
    path('pokemon/<int:pk>/update', views.Poke_Update.as_view(), name="poke_update"),
    path('pokemon/<int:pk>delete', views.Poke_Delete.as_view(), name="poke_delete"),
    path('user/<username>/', views.profile, name='profile'),
    path('pokemoves/', views.pokemoves_index, name='pokemoves_index'),
    path('pokemoves/<int:pokemove_id>', views.pokemoves_show, name='pokemoves_show'),
    path('pokemoves/create/', views.PokeMove_Create.as_view(), name='pokemoves_create'),
    path('pokemoves/<int:pk>/update/', views.PokeMove_Update.as_view(), name='pokemoves_update'),
    path('pokemoves/<int:pk>/delete/', views.PokeMove_Delete.as_view(), name='pokemoves_delete'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
TYPE_CHOICES = (
    ("Electric", "Electric"),
    ("Dragon", "Dragon"),
    ("Fire", "Fire"),
    ("Ghost", "Ghost"),
    ("Normal", "Normal"),
    ("Plant", "Plant"),
    ("Psychic", "Psychic"),
    ("Rock", "Rock"),
    ("Water", "Water"),
)


class PokeMove(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices = TYPE_CHOICES)

    def __str__(self):
        return self.name

TYPE_CHOICES = (
    ("Electric", "Electric"),
    ("Dragon", "Dragon"),
    ("Fire", "Fire"),
    ("Ghost", "Ghost"),
    ("Normal", "Normal"),
    ("Plant", "Plant"),
    ("Psychic", "Psychic"),
    ("Rock", "Rock"),
    ("Water", "Water"),
)


class Poke(models.Model):

    name = models.CharField(max_length=50)
    img = models.CharField(max_length=250)
    number = models.IntegerField()
    type = models.CharField(max_length=10, choices = TYPE_CHOICES)
    #USER implementation
    user = models.ForeignKey(User, on_delete=models.CASCADE) # 1:M example
    pokemoves = models.ManyToManyField(PokeMove) # M:M example

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    class Meta:
            ordering = ['name']

main_app/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect #Responses
from django.views.generic.base import TemplateView
from .models import Poke, PokeMove
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse
from django.contrib.auth.models import User
#Auth imports
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
class Home(TemplateView):
    template_name = 'home.html'

class About(TemplateView):
    template_name = 'about.html'

class Poke_List(TemplateView):
    template_name = 'pokelist.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #gets name query to access it
        name = self.request.GET.get("name")
        #if query exists, will filter by name
        if name != None:
            context["pokemon"] = Poke.objects.filter(name__icontains=name)
            context["header"] = f"Searching for {name}"
        else: 
            context['pokemon'] = Poke.objects.all() # this is where we add the key into our context object for the view to use
            context['header'] = "Our Pokemon"
        return context



@method_decorator(login_required, name='dispatch')
class Poke_Create(CreateView):
    model = Poke
    fields = ['name', 'img', 'number', 'type', 'user', 'pokemoves']
    template_name = "poke_create.html"
    #OLD create sucess redirect
    # success_url = "/pokemon/"
    #NEW create success redirect
    # def get_success_url(self):
    #     return reverse('poke_detail', kwargs={'pk': self.object.pk})
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/pokemon')

class Poke_Detail(DetailView):
    model = Poke
    template_name = "poke_detail.html"

@method_decorator(login_required, name='dispatch')
class Poke_Update(UpdateView):
    model = Poke
    fields = ['name', 'img', 'number', 'type', 'pokemoves']
    template_name = "poke_update.html"
    #OLD success redirect
    # success_url = "/pokemon"
    #NEW success redirect
    def get_success_url(self):
        return reverse('poke_detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class Poke_Delete(DeleteView):
    model = Poke
    template_name = "poke_delete_confirmation.html"
    success_url = "/pokemon/"

#Profile for the User
@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    pokemon = Poke.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'pokemon': pokemon})

#PokeMoves view functions
def pokemoves_index(request):
    pokemoves = PokeMove.objects.all()
    return render(request, 'pokemove_index.html', {'pokemoves': pokemoves})

def pokemoves_show(request, pokemove_id):
    pokemove = PokeMove.objects.get(id=pokemove_id)
    return render(request, 'pokemove_show.html', {'pokemove': pokemove})

@method_decorator(login_required, name='dispatch')
class PokeMove_Create(CreateView):
    model = PokeMove
    fields = '__all__'
    template_name = "pokemove_form.html"
    success_url = '/pokemoves'

@method_decorator(login_required, name='dispatch')
class PokeMove_Update(UpdateView):
    model = PokeMove
    fields = ['name', 'type']
    template_name = "pokemove_update.html"
    success_url = '/pokemoves'

@method_decorator(login_required, name='dispatch')
class PokeMove_Delete(DeleteView):
    model = PokeMove
    template_name = "pokemove_confirm_delete.html"
    success_url = '/pokemoves'

#Login, Logout, and Signup
def login_view(request):
    # if POST, then authenticate the user (submit the username and password)
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/'+u)
                else:
                    print('The account has been disabled')
                    # Feel free to redirect them somewhere 
                    return HttpResponseRedirect('/login')
        else:
            print('The username and/or password is incorrect')
            return HttpResponseRedirect('/login')
    else:
        #user is going to the login page
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/pokemon')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print('Hey', user.username)
            return HttpResponseRedirect('/user/'+str(user))
        else:
            HttpResponse('<h1>Try again...</h1>')
            return HttpResponseRedirect('/signup')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
Django Pokemon About
{% endblock %}

{% block content %}
<h1>About Page</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CDN SCRIPTS CSS go here -->
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <script src="{% static 'scripts/app.js' %}" defer></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        {% if user.is_authenticated %}
    <span><a href="{% url 'profile' user.username %}">Hello, {{ user.username }}!</a></span>
    <span> | </span>
    <span><a href="{% url 'logout' %}">Logout</a></span>
    <span> | </span>
    {% else %}
    <span><a href="{% url 'login' %}">Login</a></span>
    <span> | </span>
    <span><a href="{% url 'signup' %}">SignUp</a></span>
    {% endif %}
        <a href="/admin">Admin |</a>
        <a href="/">Home |</a>
        <a href="/about">About |</a>
        <a href="/pokemon">Pokemon |</a>
        <a href="/pokemoves">Pokemon Moves |</a>
        <a href="{% url 'poke_create' %}">Add a Pokemon |</a>
        <a href="{% url 'pokemoves_create' %}">Add a Pokemon Move |</a>
    </nav>
    {% block content %}

    {% endblock %}

</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Django Pokemon Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1>Login</h1>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>


{% endblock %}

main_app/templates/poke_delete_confirmation.html
{% extends 'base.html' %} 

{% block content %}
<h1>Are you sure you want to Delete {{poke.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <div>
   <!-- confirm poke delete -->
    <input type="submit" value="Confirm" />
    <!-- Redirect back to detail on cancel -->
    <a href="{% url 'poke_detail' poke.pk %}">Cancel</a>
  </div>
</form>
{% endblock %}

main_app/templates/poke_detail.html
{% extends 'base.html' %} 

{% block content %}

<div>
  <img src="{{poke.img}}" alt="{{poke.name}}" />
</div>
    <h1>{{poke.name}}</h1>
</div>
<div>
    <h3>Name: {{ poke.name }}</h3>
    <h3>Number: {{poke.number}}</h3>
    <h3>Type: {{poke.type}}</h3>
    <p>Adopted by:
        <a href="/user/{{ poke.user.username }}">{{ poke.user.username }}</a>
    </p>

    <h3>Moves owned:</h3>
    {% for pokemove in poke.pokemoves.all %}
        <div>{{ pokemove.name }}</div>
    {% empty %}
        <div> Pokemon has no moves 🙁</div>
    {% endfor %}
</div>

{% if user.is_authenticated %}
<div>
    <a href="{% url 'poke_update' poke.pk %}">Update</a>
    <a href="{% url 'poke_delete' poke.pk %}">Delete</a>
</div>
{% endif %}

{% endblock %}

main_app/templates/poke_update.html
{% extends 'base.html' %} 

{% block content %}
<h1>Update {{poke.name}}</h1>

<form action="" method="post">
  {% csrf_token %} 
  {{form.as_p}} 
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/pokelist.html
{% extends 'base.html' %}

{% block content %}
    <form>
        <div>
            <input type="text" name="name" placeholder="name"/>
            <input type="submit" value="Search"/>
        </div>
        <a href="{% url 'poke_list' %}">Clear Search</a>

    </form>
    <h1>{{header}}</h1>
    {% for poke in pokemon %}
    <img src="{{poke.img}}" alt="{{poke.name}}">
        <a href="{% url 'poke_detail' poke.pk %}">
            <h3>Name: {{poke.name}}</h3>
        </a>
        <h3>Number: {{poke.number}}</h3>
        <h3>Type: {{poke.type}}</h3>
        <p>Adopted by:
            <a href="/user/{{ poke.user.username }}">{{ poke.user.username }}</a>
        </p>
  
    {% endfor %}
{% endblock %}

main_app/templates/pokemove_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Pokemon Move</h1>

    <h4>Are you sure you want to delete <strong>{{ pokemove }}</strong>?</h4>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href="{% url 'pokemoves_show' pokemove.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/pokemove_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>

{% endblock %}

main_app/templates/pokemove_index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Pokemon Move List</h1>

    {% for pokemove in pokemoves %}
        <div>
            <a href="{% url 'pokemoves_show' pokemove.id %}">
                <div class="card-content">
                    <span>{{ pokemove.name }}</span>
                    <p>Type: {{ pokemove.type }}</p>
                </div>
            </a>
        </div>
        <hr/>
    {% endfor %}

{% endblock %}

main_app/templates/pokemove_show.html
{% extends 'base.html' %}

{% block content %}
    <h1>Pokemon Move Details</h1>

    <div>
        <div>
            <h2>{{ pokemove.name }}</h2>
            <p>Type: {{ pokemove.type }}</p>
            <p>Owned by:</p>
            {% for poke in pokemove.poke_set.all %}
                <p>{{ poke.name }}</p>
            {% empty %}
                <p>Nobody has this move 😝</p>
            {% endfor %}
        </div>

        <div>
            <a href="{% url 'pokemoves_update' pokemove.id %}">Edit</a>
            <a href="{% url 'pokemoves_delete' pokemove.id %}">Delete</a>
        </div>
    </div>

{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <h1>{{ username }}'s Collection</h1>

    {% for poke in pokemon %}
        <a href="/pokemon/{{ poke.id }}">
            <h3>{{ poke.name }}</h3>
        </a>

    {% endfor %}

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1>Sign Up</h1>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Sign Up">
    </form>


{% endblock %}